# Generated by Django 4.1.4 on 2022-12-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='rank',
            field=models.CharField(max_length=50),
        ),
    ]
