# Generated by Django 4.1.4 on 2022-12-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_app', '0002_alter_team_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='img',
            field=models.ImageField(default=123, upload_to='gallery'),
            preserve_default=False,
        ),
    ]
